name: $(Rev:rrrrr)
pool:
  name: CSG OnPrem VS2019
trigger:
- master
- rel/*
- v2.0
steps:
- task: PowerShell@1
  displayName: 'Build'
  inputs:
    scriptName: build.ps1
    arguments: '-NoTest'
- task: DotNetCoreCLI@2
  displayName: 'Test'
  inputs:
    command: test
    projects: 'tests\**\*Tests.csproj'
    arguments: '--no-build --configuration Release'
    verbosityPack: Minimal
- task: CopyFiles@2
  displayName: 'Copy nupkgs'
  inputs:
    Contents: '**\bin\**\*.nupkg'
    TargetFolder: '$(Build.ArtifactStagingDirectory)\nupkgs'
    CleanTargetFolder: true
    flattenFolders: true
- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: nupkgs'
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)\nupkgs'
    ArtifactName: nupkgs
